SUBROUTINE MBSC.Tempp.LOAD
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_MBSC.Tempp.COMMON
    $INSERT I_F.FUNDS.TRANSFER
    $INSERT I_F.MBSC.Temp

    FN.FT='F.FUNDS.TRANSFER'
    FN.MBSC.Temp='F.MBSC.Temp'
    FN.ACC='F.ACCOUNT'
    CALL OPF(FN.FT,F.FT)
    CALL OPF(FN.MBSC.Temp,F.MBSC.Temp)
    CALL OPF(FN.ACC,F.ACC)
    
END