PROGRAM ALI_FT_WRITE_TEST_VALIDATION
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.FUNDS.TRANSFER
    FN.FT='F.FT'
    F.FT=''
    CALL OPF(FN.FT,F.FT)
    TEST.ID='FT2999999002'
    R.FT=''
    R.FT<FT.DEBIT.CURRENCY>='USD'
    R.FT<FT.CREDIT.CURRENCY>='EUR'
    WRITE R.FT ON F.FT, TEST.ID
    CRT 'WROTE RECORD WITH MISMATCHED CURRENCIES - FT.VALIDATION.RTN NEVER RAN'
    CRT 'DEBIT.CURRENCY=':R.FT<FT.DEBIT.CURRENCY>:' CREDIT.CURRENCY=':R.FT<FT.CREDIT.CURRENCY>
END
