PROGRAM ALI_FT_WRITE_TEST_INPUT
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.FUNDS.TRANSFER
    FN.FT='F.FT'
    F.FT=''
    CALL OPF(FN.FT,F.FT)
    TEST.ID='FT2999999003'
    R.FT=''
    WRITE R.FT ON F.FT, TEST.ID
    CRT 'WROTE RECORD WITH BLANK DEBIT.VALUE.DATE - FT.INPUT.RTN NEVER RAN TO DEFAULT IT'
    CRT 'DEBIT.VALUE.DATE=[':R.FT<FT.DEBIT.VALUE.DATE>:'] (should be empty)'
END
