PROGRAM ALI_FT_WRITE_TEST_ID
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.FUNDS.TRANSFER
    FN.FT='F.FT'
    F.FT=''
    CALL OPF(FN.FT,F.FT)
    BAD.ID='FT2999999001'
    R.FT=''
    WRITE R.FT ON F.FT, BAD.ID
    CRT 'WROTE RECORD WITH BAD JULIAN DATE ID - FT.ID.RTN NEVER RAN'
    CRT 'ID USED: ':BAD.ID
END
