PROGRAM ALI_FT_WRITE_TEST_AUTH
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.FUNDS.TRANSFER
    FN.FT='F.FT'
    F.FT=''
    CALL OPF(FN.FT,F.FT)
    TEST.ID='FT2999999004'
    R.FT=''
    R.FT<FT.DEBIT.AMOUNT>=500000
    WRITE R.FT ON F.FT, TEST.ID
    CRT 'WROTE RECORD WITH AMOUNT OVER LIMIT - FT.AUTH.RTN NEVER RAN'
    CRT 'DEBIT.AMOUNT=':R.FT<FT.DEBIT.AMOUNT>:' (never checked against authorisation limit)'
END