SUBROUTINE FT.AUTH.RTN
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.FUNDS.TRANSFER
    IF R.NEW<FT.DEBIT.AMOUNT> GT 100000 THEN
        ETEXT='AMOUNT EXCEEDS AUTHORISATION LIMIT'
        CALL STORE.END.ERROR
    END
RETURN
END
