SUBROUTINE FT.INPUT.RTN
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.FUNDS.TRANSFER
    IF R.NEW<FT.DEBIT.VALUE.DATE> EQ '' THEN
        R.NEW<FT.DEBIT.VALUE.DATE> = TODAY
    END
    IF R.NEW<FT.CREDIT.VALUE.DATE> EQ '' THEN
        R.NEW<FT.CREDIT.VALUE.DATE> = TODAY
    END
RETURN
END