SUBROUTINE FT.VALIDATION.RTN
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.FUNDS.TRANSFER
    IF R.NEW<FT.DEBIT.CURRENCY> NE R.NEW<FT.CREDIT.CURRENCY> THEN
        AF=FT.CREDIT.CURRENCY
        ETEXT='DEBIT AND CREDIT CURRENCY MUST MATCH'
        CALL STORE.END.ERROR
    END
RETURN
END
