SUBROUTINE MBSC.BATCH.SELECT
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_MBSC.BATCH.COMMON
    $INSERT I_F.FUNDS.TRANSFER
    $INSERT I_F.MBSC.BATCH2
    
   
    SEL.CMD = 'SELECT ':F.ACCOUN:' WITH CATEGORY EQ 1001 AND CURRENCY EQ USD'

    CALL EB.READLIST (SEL.CMD, SEL.LIST.ID, '', NO.OF.REC, SEL.ERR)
    CALL BATCH.BUILD.LIST('', SEL.LIST.ID)
  
END
