SUBROUTINE MBSC.BATCH.LOAD
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_MBSC.BATCH.COMMON
    $INSERT I_F.FUNDS.TRANSFER
    $INSERT I_F.MBSC.HAGER
    
    FN.FT='F.FUNDS.TRANSFER'
    FN.MBSC.HAGER='F.MBSC.HAGER'
    FN.ACCOUNT='F.ACCOUNT'
    CALL OPF(FN.FT,F.FT)
    CALL OPF(FN.MBSC.HAGER,F.MBSC.HAGER)
    CALL OPF(FN.ACCOUNT,F.ACCOUNT)
      
RETURN

END
