SUBROUTINE FT.ID.RTN
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.DATES
    
    FN.DATES='F.DATES'
    F.DATES=''
    CALL OPF(FN.DATES,F.DATES)
    CALL F.READ(FN.DATES,'AU0010001',R.DATE,F.DATES,R.D.ERR)
    
    
    JUL.DATE=R.DATE(EB.DAT.JULIAN.DATE)
    ID=COMI
    IF LEN(ID) > 13 THEN
        E='ID LENGTH IS INVALID'
    END
    IF ID[3,6] NE '22109' THEN
        E='JULIAN DATE IS INCORRECT'
    END
      
RETURN
END
 