SUBROUTINE MBSC.InfoBasicMT.SELECT
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_MBSC.InfoBasicMT.COMMON
    $INSERT I_F.FUNDS.TRANSFER
    $INSERT I_F.MBSC.InfoBasicTemp
    
    
    FN.ACC='F.ACCOUNT'
    CALL OPF(FN.ACC,F.ACC)
    
    SEL.CMD = 'SELECT ':F.ACC:' WITH CATEGORY EQ 1001 AND CURRENCY EQ EUR'

    CALL EB.READLIST (SEL.CMD, SEL.LIST.ID, '', NO.OF.REC, SEL.ERR)
    CALL BATCH.BUILD.LIST('', SEL.LIST.ID)
END
