SUBROUTINE FT.ID.RTN
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.DATES

    FN.DATES = 'F.DATES'
    F.DATES = ''
    CALL OPF(FN.DATES, F.DATES)
    CALL F.READ(FN.DATES, 'AUB810801', R.DATE, F.DATES, R.D.ERR)
    JUL.DATE = R.DATE<EB.DAT.JULIAN.DATE>

    ID.NEW = COMI

    IF LEN(ID.NEW) GT 13 THEN
        E = 'ID LENGTH IS INVALID'
    END

    IF ID.NEW[3,6] NE JUL.DATE THEN
        E = 'JULIAN DATE IS INCORRECT'
    END

RETURN
END