SUBROUTINE FT.VALIDATION.RTN
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.FUNDS.TRANSFER
    DEPT.CUR = COMI
    IF DEPT.CUR NE 'USD' THEN
        ETEXT = 'DEBIT CURRENCY MUST BE USD'
        CALL STORE.END.ERROR
    END

RETURN
END
