SUBROUTINE FT.VAL.INPUT
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.FUNDS.TRANSFER


    COMMISSION = R.NEW<FT.COMMISSION.CODE>

    IF COMMISSION NE 'WAIVED' THEN
        TEXT = 'COMMISSION HAS BEEN WAIVED'
        CURR.NO = ''
        CALL STORE.OVERRIDE(CURR.NO)
    END
END
