SUBROUTINE MBSC.BATCH.LOAD
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_MBSC.BATCH.COMMON
    $INSERT I_F.FUNDS.TRANSFER
    $INSERT I_F.MBSC.BATCH2
    $INSERT I_F.ACCOUNT
  
    FN.FT = 'F.FUNDS.TRANSFER'
    FN.MBSC.BATCH2 = 'F.MBSC.BATCH2'
    FN.ACCOUNT = 'F.ACCOUNT'
    CALL OPF(FN.FT, F.FT)
    CALL OPF(FN.MBSC.BATCH2, F.MBSC.BATCH2)
    CALL OPF(FN.ACCOUNT, F.ACCOUNT)
 
RETURN
END
 