SUBROUTINE FT.LOCK.EVENT
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.FUNDS.TRANSFER
    $INSERT I_F.AC.LOCKED.EVENTS
    
    FT.ID = ID.NEW
    DBT.ACC = R.NEW(FT.DEBIT.ACCT.NO)
    DBT.AMT = R.NEW(FT.DEBIT.AMOUNT)
    
    R.AC.LOCK = ''
    R.AC.LOCK<AC.LCK.ACCOUNT.NUMBER> = DBT.ACC
    R.AC.LOCK<AC.LCK.LOCKED.AMOUNT> = DBT.AMT
    R.AC.LOCK<AC.LCK.DESCRIPTION> = FT.ID
    
* OFS
    OFS.MSG = ''
    TRANSACTION.ID  = ''
    Y.APPLICATION   = 'AC.LOCKED.EVENTS'
    Y.FUNC          = 'I'
    Y.OPER          = 'PROCESS'
    Y.VERSION       = "AC.LOCKED.EVENTS,"
    Y.GTS.MODE      = '1'
    Y.NO.OF.AUTH    = '0'
    Y.OFS.SOURCE    = "BULK.OFS"
    Y.THE.RESPONSE  = ''
    Y.TXN.RESULT    = ''
    OPTNS           = ''
    MSG.ID          = ''

    CALL OFS.BUILD.RECORD(Y.APPLICATION,Y.FUNC,Y.OPER,Y.VERSION,Y.GTS.MODE,Y.NO.OF.AUTH,TRANSACTION.ID,R.AC.LOCK,OFS.MSG)

    CALL OFS.CALL.BULK.MANAGER(Y.OFS.SOURCE,OFS.MSG,Y.THE.RESPONSE,Y.TXN.RESULT)



END
