SUBROUTINE FT.VAL.TXN.TYPE
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.FUNDS.TRANSFER
    
    TXN.TYPE = R.NEW(FT.TRANSACTION.TYPE)
    
    IF TXN.TYPE NE 'AC' THEN
        TEXT = 'FT.MBSC.TXN.TYPE'
        
        CURR.NO = ''
        CALL STORE.OVERRIDE (CURR.NO)
    END

END
