SUBROUTINE FT.VAL.CUR
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.FUNDS.TRANSFER
    
    DEBT.CUR = R.NEW (FT.DEBIT.CURRENCY)
    
    IF DEBT.CUR NE 'USD' THEN
        ETEXT = 'FT-MBSC.CUR'
        CALL STORE.END.ERROR
    END

END
