SUBROUTINE TASK8.TASK8.SELECT

    $INSERT I_TASK8.TASK8.COMMON
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.FUNDS.TRANSFER
    $INSERT I_F.TASK7.TASK7
    
    SEL.CMD='SELECT':F.ACC:' WITH CATEGORY EQ 1001 AND CURRENCY EQ USD'
    
    CALL EB.READLIST(SEL.CMD, SEL.LIST.ID, '', NO.OF.REC, SEL.ERR)
    
    CALL BATCH.BUILD.LIST('', SEL.LIST.ID)
    
RETURN
END
