SUBROUTINE TASK8.EASK8(SEL.LIST.ID)
    
    $INSERT I_TASK8.TASK8.COMMON
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.FUNDS.TRANSFER
    $INSERT I_F.TASK7.TASK7
    
    R.FT=''
    R.FT<FT.TRANSACTION.TYPE>= 'AC'
    R.FT<FT.DEBIT.ACCT.NO>=SEL.LIST.ID
    R.FT<FT.DEBIT.CURRENCY>='USD'
    R.FT<FT.DEBIT.AMOUNT>='10'
    R.FT<FT.CREDIT.ACCT.NO>='USD1090515070001'
    
*---------------------OFS---------------------------*
    
    OFS.MSG=''
    TRANSACTION.ID=''
    Y.APPLICATION='FUNDS.TRANSFER'
    Y.FUNC='I'
    Y.OPER='PROCESS'
    Y.VERSION='FUNDS.TRANSFER,'
    Y.GTS.MODE='1'
    Y.NO.OF.AUTH='0'
    Y.OFS.SOURCE='TASK8'
    Y.THE.RESPONSE=''
    Y.TXN.RESULT=''
    OPTNS=''
    MSG.ID=''
    
    CALL OFS.BUILD.RECORD(Y.APPLICATION,Y.FUNC,Y.OPER,Y.VERSION,Y.GTS.MODE,Y.NO.OF.AUTH,TRANSACTION.ID,R.FT,OFS.MSG)
    CALL OFS.CALL.BULK.MANAGER(Y.OFS.SOURCE, OFS.MSG, Y.THE.RESPONSE, Y.TXN.RESULT)
    
    
RETURN
END
