SUBROUTINE TASK8.TASK8.LOAD
    $INSERT I_TASK8.TASK8.COMMON
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.FUNDS.TRANSFER
    $INSERT I_F.TASK7.TASK7

    FN.FT='F.FUNDS.TRANSFER'
    FN.TASK7.TASK7='F.TASK7.TASK7'
    FN.ACC='F.ACCOUNT'
    CALL OPF(FN.FT,F.FT)
    CALL OPF(FN.TASK7.TASK7,F.TASK7.TASK7)
    CALL OPF (FN.ACC, F.ACC)
    
RETURN
END
