SUBROUTINE CheckIdLength
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.FUNDS.TRANSFER
    
    ID = COMI
    IF LEN(ID) > 13 THEN
        E='FT ID LENGTH SHOULD NOT EXCEED 13 CHARACTERS'
    END
RETURN
END
