SUBROUTINE FT.AUTHORIZE
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.FUNDS.TRANSFER
    $INSERT I_F.AC.LOCKED.EVENTS
    
    
    DEBT.ACC= R.NEW(FT.DEBIT.ACCT.NO)
    DEBT.AMNT = R.NEW(FT.DEBIT.AMOUNT)
    
    R.AC.LOCK=''
    R.AC.LOCK<AC.LCK.ACCOUNT.NUMBER>= DEBT.ACC
    R.AC.LOCK<AC.LCK.LOCKED.AMOUNT>=DEBT.AMNT
    
    OFS.MSG=''
    TRANSACTION.ID =''
    Y.APPLICATION  ='AC.LOCKED.EVENTS'
    Y.FUNC = 'I'
    Y.OPER ='PROCESS'
    Y.VERSION ='AC.LOCKED.EVENTS,'
    Y.GTS.MODE = '1'
    
    Y.NO.OF.AUTH ='0'
    Y.OFS.SOURCE= 'BULK.OFS'
    Y.THE.RESPONSE=''
    Y.TXN.RESULT=''
    
    CALL OFS.BUILD.RECORD(Y.APPLICATION,Y.FUNC,Y.OPER,Y.VERSION,Y.GTS.MODE,Y.NO.OF.AUTH,TRANSACTION.ID,R.AC.LOCK,OFS.MSG)
    CALL OFS.CALL.BULK.MANAGER(Y.OFS.SOURCE,OFS.MSG,Y.THE.RESPONSE,Y.TXN.RESULT)


END
