SUBROUTINE FT.INPUT
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.FUNDS.TRANSFER
    
    COMM.TYPE = R.NEW(FT.COMMISSION.CODE)
    
    IF COMM.TYPE EQ 'WAIVE' THEN
        TEXT='COMMISSION HAS BEEN WAIVED'
        CURR.NO=''
        CALL STORE.OVERRIDE(CURR.NO)
    END
RETURN
END
