SUBROUTINE FT.VALIDATE.RTN
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_F.FUNDS.TRANSFER
    
    DEP.CURR = R.NEW(5)
    
    IF DEP.CURR NE 'USD' THEN
        ETEXT='DEBT CURRENCY SHOULD BE USD'
        CALL STORE.END.ERROR
    END
END
