SUBROUTINE ALI.SERVICE.SELECT
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_ALI.SERVICE.COMMON
    $INSERT I_F.FUNDS.TRANSFER
    $INSERT I_F.ALI.FT.TEMPLATE
    
    
    
    
RETURN

END
