SUBROUTINE ALI.SERVICE.LOAD
    $INSERT I_COMMON
    $INSERT I_EQUATE
    $INSERT I_ALI.SERVICE.COMMON
    $INSERT I_F.FUNDS.TRANSFER
    $INSERT I_F.ALI.FT.TEMPLATE
    FN.FT='F.FUNDS.TRANSFER'
    FN.ALI.FT.TEMPLATE='F.ALI.FT.TEMPLATE'
    CALL OPF(FN.FT,F.FT)
    CALL OPF(FN.ALI.FT.TEMPLATE,F.ALI.FT.TEMPLATE)

    
    




END
